apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nestjs-bp
  name: nestjs-bp-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nestjs-bp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nestjs-bp
      namespace: default
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
          image: keithstric/nestjs-boilerplate
          imagePullPolicy: Always
          name: nestjs-bp
          ports:
            - containerPort: 3000
              hostIP: 10.0.0.158
              hostPort: 30001
              name: nestjs-bp-svc
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 3000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
